name: Una cena
rules:
  - { image: Fondo.png      , when: { black: 0, blue:  0, green: 0, red: 0 } }
  - { image: Hamburguesa.png, when: { black: 0, blue: 11, green: 0, red: 0 } }
  - { image: Papas.png      , when: { black: 0, blue: 21, green: 0, red: 0 } }
  - { image: Torta.png      , when: { black: 0, blue: 31, green: 0, red: 0 } }
  - { image: Cafe.png       , when: { black: 0, blue: 41, green: 0, red: 0 } }
  - { image: Bife.png       , when: { black: 0, blue: 10, green: 0, red: 0 } }
  - { image: Ensalada.png   , when: { black: 0, blue: 20, green: 0, red: 0 } }
  - { image: Durazno.png    , when: { black: 0, blue: 30, green: 0, red: 0 } }
  - { image: AunNo.png      , when: { black: 0, blue:  0, green: 0, red: 1 } }
  - { image: Vengan.png     , when: { black: 0, blue:  0, green: 1, red: 0 } }
